"""PROTOTYPE, throwaway (#17). Rebuild every blockout variant and the gallery data.

  python3 assets-src/maps/prototype-blockouts/build_all.py [variant ...] [--quick]

Runs headless Blender once per variant (writes out/glb/*.glb, out/img/*.jpg, out/*.json), then
gathers the JSON into out/gallery-data.js for gallery.html.
"""
import json, os, subprocess, sys, time

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "out")
ALL = ["skate_park_ba", "skate_park_a", "skate_park_b", "skate_park_c", "bando_a_rooms", "bando_a", "bando_b", "bando_c"]
BLENDER = os.environ.get("BLENDER", "blender")

args = [a for a in sys.argv[1:] if not a.startswith("--")]
flags = [a for a in sys.argv[1:] if a.startswith("--")]
t0 = time.time()
for key in args or ALL:
    cmd = [BLENDER, "--background", "--factory-startup", "--python-exit-code", "1",
           "--python", os.path.join(HERE, "run_variant.py"), "--", key, OUT, *flags]
    r = subprocess.run(cmd, capture_output=True, text=True)
    done = [l for l in r.stdout.splitlines() if l.startswith(f"[{key}]")]
    print(done[0] if done else f"[{key}] FAILED\n{r.stdout[-3000:]}\n{r.stderr[-3000:]}")
    if r.returncode:
        sys.exit(r.returncode)

data = [json.load(open(os.path.join(OUT, f"{k}.json"))) for k in ALL if os.path.exists(os.path.join(OUT, f"{k}.json"))]
with open(os.path.join(OUT, "gallery-data.js"), "w") as fh:
    fh.write("// Generated by build_all.py. PROTOTYPE data for gallery.html.\n")
    fh.write("window.BLOCKOUTS = " + json.dumps(data, indent=1) + ";\n")
print(f"gallery data: {len(data)} variants, {time.time() - t0:.1f}s total")
